##################
# binning_mapping.sub
# Submission script for mapping metagenomic
# reads to the scaffolds from the assemblies
# that will be used for binning.

# Benjamin D. Peterson
##################

request_cpus = 12
request_memory = 120GB

executable = /home/GLBRCORG/bpeterson26/BLiMMP/code/binning_mapping.sh

environment = "assembly=$(assembly) \
              mapping=/home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/binning/mapping \
              scaffoldsLocation=/home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/binning/scaffolds \
              metagenomeLocation=/home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/metagenomes \
              mappingKey=/home/GLBRCORG/bpeterson26/BLiMMP/metadata/mapping_key.tsv"
output = /home/GLBRCORG/bpeterson26/BLiMMP/reports/binning_mapping/outs/$(assembly)_binningMapping.out
error = /home/GLBRCORG/bpeterson26/BLiMMP/reports/binning_mapping/errs/$(assembly)_binningMapping.err
log = /home/GLBRCORG/bpeterson26/BLiMMP/reports/binning_mapping/logs/$(assembly)_binningMapping.log

queue assembly from /home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/binning/assembly_list_to_use.txt
