---
title: "BLiMMP Water Column Characteristics"
author: "Benjamin D. Peterson"
date: "2023-01-02"
output: html_document
---

```{r, setup, include = FALSE}
knitr::opts_knit$set(echo = TRUE)
new.wd <- gsub("\\/[[:alpha:]]+$", "", getwd())
knitr::opts_knit$set(root.dir = new.wd)
```

```{r, load_functions, include = FALSE}
getwd()
source("code/BLiMMP_functions.R")
```

### Temperature heatmaps and sampling locations

```{r temperature heatmaps, echo = FALSE}
# Read in data
library(readxl)
temperature.data <- read.csv("dataFinal/tempurature_buoy_data.csv")
sampling.location.info <- read_xlsx("dataEdited/incubations/incubation_sites_notes.xlsx")


# Temp profile for 2020
temp.profile.thermocline(data.of.interest = temperature.data,
                         year.of.interest = 2020,
                         starting.date = "2020-04-30",
                         ending.date = "2020-11-05",
                         sampling.date.location.df.to.use = sampling.location.info)
# Temp profile for 2021
temp.profile.thermocline(data.of.interest = temperature.data,
                         year.of.interest = 2021,
                         starting.date = "2021-04-30",
                         ending.date = "2021-11-05",
                         sampling.date.location.df.to.use = sampling.location.info)

```



### Onset of anoxia

```{r DO profiles, echo = FALSE}
# Read in data
DO.data <- read.csv("dataFinal/DO_profiles_data.csv")

# Make date vector
date.vector <- c("May 1st", "Jun 1st", "July 1st", "August 1st")
date.naming.vector <- yday(mdy(paste(date.vector, ", 2017",
                                     sep = "")))
names(date.naming.vector) <- date.vector

# DO profile for 2020
DO.heatmap(DO.profile.data = DO.data,
           year.of.interest = "2020",
           date.limits = c("2020-05-01", "2020-08-01"))
DO.heatmap(DO.profile.data = DO.data,
           year.of.interest = "2021",
           date.limits = c("2021-05-01", "2021-08-01"))
```



### Biogeochemical profiles on days of sampling for incubations

```{r biogeochemical profile, echo = FALSE, fig.height = 16, fig.width = 8}
# Read in data
incubation.depths <- read.csv("metadata/processedMetadata/incubation_metadata.csv") %>%
  select(startDate, depth) %>%
  unique()
exo.data <- read.csv("dataFinal/exo_data.csv")
waterChem.data <- read.csv("dataFinal/water_chem_data.csv")

#### Define function: To combine plots for a specific date ####
generate_geochem_plots <- function(date.of.interest,
                                   sampling.depths.of.interest = NULL) {

  sampling.depths.of.interest <- incubation.depths %>%
    filter(startDate == date.of.interest) %>%
    select(depth) %>%
    unlist(use.names = FALSE)
  # Plot sonde casts
  plot.exo.data(exo.data.to.use = exo.data,
                date.of.sampling = date.of.interest,
                legend.location = "bottomleft",
                points.of.sampling = sampling.depths.of.interest)

  # Plot metals data
  color.vector <- c(cb.translator["orange"], cb.translator["orange"],
                    cb.translator["yellow"], cb.translator["yellow"])
  names(color.vector) <- c("Mn_diss_ppm", "Mn_part_ppm",
                           "Fe_diss_ppm", "Fe_part_ppm")
  point.vector <- c(16, 1, 16, 1)
  names(point.vector) <- names(color.vector)
  line.vector <- c(1, 2, 1, 2)
  names(line.vector) <- names(color.vector)
  naming.vector <- c("Diss. Mn (ppm)", "Part. Mn (ppm)",
                     "Diss. Fe (ppm)", "Part. Fe (ppm)")
  names(line.vector) <- names(color.vector)
  plot.chem.data(icp.data.to.use = waterChem.data,
                   color.vector.to.use = color.vector,
                   point.vector.to.use = point.vector,
                   line.vector.to.use = line.vector,
                   naming.vector.to.use = naming.vector,
                   xlim.to.use = c(0, 0.4),
                   date.of.sampling = date.of.interest)

  # Plot sulfate/sulfide data
  color.vector <- c(cb.translator["blue"], cb.translator["blue"])
  names(color.vector) <- c("sulfate_uM", "sulfide_uM")
  point.vector <- c(1, 16)
  names(point.vector) <- names(color.vector)
  line.vector <- c(2, 1)
  names(line.vector) <- names(color.vector)
  naming.vector <- c("Sulfate (µM)", "Sulfide (µM)")
  names(line.vector) <- names(color.vector)
  plot.chem.data(icp.data.to.use = waterChem.data,
                 color.vector.to.use = color.vector,
                 point.vector.to.use = point.vector,
                 line.vector.to.use = line.vector,
                 naming.vector.to.use = naming.vector,
                 xlim.to.use = c(0, 250),
                 date.of.sampling = date.of.interest,
                 xlab.to.use = "Sulfate/Sulfide (µM)")

  # Plot Hg data
  color.vector <- c(cb.translator["vermillion"], cb.translator["bluishgreen"])
  names(color.vector) <- c("FMHG_NG.L", "FiHg_NG.L")
  point.vector <- c(16, 1)
  names(point.vector) <- names(color.vector)
  line.vector <- c(1, 2)
  names(line.vector) <- names(color.vector)
  naming.vector <- c("FP MeHg (ng/L)", "FP iHg (ng/L)")
  names(line.vector) <- names(color.vector)
  plot.chem.data(icp.data.to.use = waterChem.data,
                 color.vector.to.use = color.vector,
                 point.vector.to.use = point.vector,
                 line.vector.to.use = line.vector,
                 naming.vector.to.use = naming.vector,
                 xlim.to.use = c(0, 1.2),
                 date.of.sampling = date.of.interest,
                 xlab.to.use = "Hg (ng/L)")

}
par(mfrow = c(4, 4),
    mar = c(9, 3, 2.5, 1),
    mgp = c(1.5, 0.4, 0),
    tck = -0.008)

generate_geochem_plots(date.of.interest = "2020-09-02")
generate_geochem_plots(date.of.interest = "2020-10-10")
generate_geochem_plots(date.of.interest = "2021-09-10")
generate_geochem_plots(date.of.interest = "2021-10-14")

```


### Plot DGM profiles


```{r DGM profile, echo = FALSE, fig.height = 4, fig.width = 6}
waterChem.data <- read.csv("dataFinal/water_chem_data.csv")

# Plot DGM data
color.vector <- c(cb.translator["orange"])
names(color.vector) <- c("DGM_NG.L")
point.vector <- c(17)
names(point.vector) <- names(color.vector)
line.vector <- c(1)
names(line.vector) <- names(color.vector)
naming.vector <- c("DGM (ng/L)")
names(line.vector) <- names(color.vector)
DGM.profile <- function(x) {
  plot.chem.data(icp.data.to.use = waterChem.data,
                 color.vector.to.use = color.vector,
                 point.vector.to.use = point.vector,
                 line.vector.to.use = line.vector,
                 naming.vector.to.use = naming.vector,
                 xlim.to.use = c(0, 0.040),
                 date.of.sampling = x,
                 xlab.to.use = "Hg (ng/L)")
    text(x = 4,
         y = 1.5,
         cex = 1.2,
         labels = paste(month(x, label = TRUE), " ",
                        day(x), ", ",
                        year(x),
                        sep = ""))
    }
par(mfrow = c(1, 2),
    mar = c(3, 3, 1, 1),
    mgp = c(1.5, 0.4, 0),
    tck = -0.008)
DGM.profile("2021-09-10")
DGM.profile("2021-10-14")
```
  
  