##################
# SCG_abundance_in_assemblies.sub
# Submission script for pulling out the abundances of
# single copy genes (SCGs) from metagenomes.

# Benjamin D. Peterson
##################

request_cpus = 8
request_memory = 80GB

executable = /home/GLBRCORG/bpeterson26/BLiMMP/code/SCG_abundance_in_assemblies.sh

environment = "geneName=$(geneName) \
                scripts=/home/GLBRCORG/bpeterson26/BLiMMP/code \
                scgHmms_location=/home/GLBRCORG/bpeterson26/BLiMMP/references/rp16 \
                scgHmms_key=/home/GLBRCORG/bpeterson26/BLiMMP/references/scg_key.csv \
                assembly_list=/home/GLBRCORG/bpeterson26/BLiMMP/metadata/assembly_list.txt \
                assembly_location=/home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/assemblies/ORFs \
                metagenome_list=/home/GLBRCORG/bpeterson26/BLiMMP/metadata/metagenome_list.txt \
                metagenome_location=/home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/mapping \
                output_directory=/home/GLBRCORG/bpeterson26/BLiMMP/dataEdited/scg_abundance"

output = /home/GLBRCORG/bpeterson26/BLiMMP/reports/scgAbund/outs/$(geneName).out
error = /home/GLBRCORG/bpeterson26/BLiMMP/reports/scgAbund/errs/$(geneName).err
log = /home/GLBRCORG/bpeterson26/BLiMMP/reports/scgAbund/logs/$(geneName).log

queue geneName from /home/GLBRCORG/bpeterson26/BLiMMP/references/scg_list.txt
