##################
# submit_SCG_abundance_in_assemblies.sub
# Submission script for pulling out the abundances of
# single copy genes (SCGs) from metagenomes.

# Benjamin D. Peterson
##################

request_cpus = 8
request_memory = 80GB

executable = /home/GLBRCORG/bpeterson26/BLiMMP/code/execute_SCG_abundance_in_assemblies.sh

environment = "geneName=$(geneName)"

output = /home/GLBRCORG/bpeterson26/BLiMMP/reports/scg_coverage/outs/$(geneName)_SiCoGeCo.out
error = /home/GLBRCORG/bpeterson26/BLiMMP/reports/scg_coverage/errs/$(geneName)_SiCoGeCo.err
log = /home/GLBRCORG/bpeterson26/BLiMMP/reports/scg_coverage/logs/$(geneName)_SiCoGeCo.log

queue geneName from /home/GLBRCORG/bpeterson26/BLiMMP/references/scg_list.txt
